spring:
  data:
  mongodb:
    url: mongodb+srv://mdshahidans2005_db_user:Shahid123@cluster0.yvjbs2l.mongodb.net/?appName=Cluster0
    database: journaldb
    auto-index-creation: true

  server:
    port: 8080
    servlet:
      context-path: /journal
