spring:
  data:
  mongodb:
    url: mongodb+srv://mdshahidans2005_db_user:Shahid123@cluster0.yvjbs2l.mongodb.net/?appName=Cluster0
    database: journaldb
    auto-index-creation: true
mail:
  host: stmp.gmail.com
  port: 587
  username: mdshahidans2005@@gmail.com
  password: hkpl dnqn syts foms
  properties:
    mail:
      smtp:
        auth: true
        starttls:
        enable: true
  server:
    port: 8080
    servlet:
      context-path: /journal
weather:
  api:
    key:d266ddb33db035eacae6fc65f54ae036
  redis:
    host: localhost
    port: 6379